apiVersion: v1
kind: Service
metadata:
  name: {{ include "romm.frontend.fullname" . }}
  labels:
    {{- include "romm.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
