# Backend-only image for RomM
ARG ALPINE_VERSION=3.22
ARG PYTHON_VERSION=3.13
ARG PYTHON_ALPINE_SHA256=e5fa639e49b85986c4481e28faa2564b45aa8021413f31026c3856e5911618b1
ARG UV_VERSION=0.8.24
ARG UV_SHA256=779f3d612539b4696a1b228724cd79b6e8b8604075a9ac7d15378bccf4053373

FROM python:${PYTHON_VERSION}-alpine${ALPINE_VERSION}@sha256:${PYTHON_ALPINE_SHA256} AS python-alias

# https://github.com/astral-sh/uv/pkgs/container/uv/452595714
FROM ghcr.io/astral-sh/uv:${UV_VERSION}-python${PYTHON_VERSION}-alpine@sha256:${UV_SHA256} AS uv-stage

FROM python-alias AS backend-build

RUN apk add --no-cache \
    gcc \
    git \
    libpq-dev \
    mariadb-connector-c-dev \
    musl-dev

COPY --from=uv-stage /usr/local/bin/uv /usr/local/bin/uvx /bin/

WORKDIR /app
COPY ./pyproject.toml ./uv.lock /app/
ENV UV_LINK_MODE=copy
RUN uv sync --locked --no-cache --no-dev

# Custom RAHasher
FROM alpine:${ALPINE_VERSION} AS rahasher-build
RUN apk add --no-cache \
    g++ \
    git \
    linux-headers \
    make \
    zlib-dev

ARG RALIBRETRO_VERSION=1.8.1

RUN git clone --recursive --branch "${RALIBRETRO_VERSION}" --depth 1 https://github.com/RetroAchievements/RALibretro.git && \
    cd ./RALibretro && \
    sed -i '22a #include <ctime>' ./src/Util.h && \
    sed -i '6a #include <unistd.h>' \
      ./src/libchdr/deps/zlib-1.3.1/gzlib.c \
      ./src/libchdr/deps/zlib-1.3.1/gzread.c \
      ./src/libchdr/deps/zlib-1.3.1/gzwrite.c && \
    make HAVE_CHD=1 -f ./Makefile.RAHasher

FROM python-alias AS backend-runtime

RUN apk add --no-cache \
    bash \
    libmagic \
    mariadb-connector-c \
    libpq \
    7zip \
    tzdata

WORKDIR /app

COPY --from=backend-build /app/.venv /app/.venv
COPY --from=rahasher-build /RALibretro/bin64/RAHasher /usr/bin/RAHasher
COPY ./backend /app/backend
COPY ./docker/backend-entrypoint.sh /app/backend-entrypoint.sh

ENV PATH="/app/.venv/bin:${PATH}"
ENV ROMM_BASE_PATH=/romm

RUN chmod +x /app/backend-entrypoint.sh

EXPOSE 5000

ENTRYPOINT ["/app/backend-entrypoint.sh"]
