load_module modules/ngx_http_js_module.so;

worker_processes auto;
pid /tmp/nginx.pid;

events {
    worker_connections 768;
    multi_accept on;
}

http {
    client_body_temp_path /tmp/client_body 1 2;
    proxy_temp_path /tmp/proxy;

    sendfile on;
    client_max_body_size 0;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    js_import /etc/nginx/js/decode.js;

    access_log /dev/stdout;
    error_log /dev/stderr;

    gzip on;
    gzip_vary on;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_min_length 1024;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    include /etc/nginx/conf.d/*.conf;
}
